<?php
//session_start();
require dirname(__DIR__) . '/vendor/autoload.php';
//require dirname(__DIR__) . '/controller.php';
require dirname(__DIR__) . '/models/model_login.php';

class login extends Controller {


    public function action()
    {
        parent::action(); // TODO: Change the autogenerated stub
        $this->view->render('login_view.php', 'template_view.php');

        if (!empty($_COOKIE['auth'])) {
            $_SESSION['auth'] = true;
        }

        $isAuth = !empty($_SESSION['auth']);
        if ($isAuth) {
            $_GET['url'] = 'lk';
//            header("Location:"  . );
            exit();
        }
    }

    public function entry() {

        $selLog = new Model_Login();
        $logId = $selLog->selectLog1();
        $log = $selLog->selectLog2();
        $logPass = $selLog->selectLog3();

        if (!empty($_POST['log'])) {

//        $remoteIp = $_SERVER['REMOTE_ADDR'];
//        $gRecaptchaResponse = $_REQUEST['g-recaptcha-response'];
//        $secret = '6LfMIQ0UAAAAALN5yv0aY6kYwiNRZpI_yV75FCAB';
//
//        $recaptcha = new \ReCaptcha\ReCaptcha($secret);
//        $resp = $recaptcha->verify($gRecaptchaResponse, $remoteIp);
//        if ($resp->isSuccess()) {
//            // verified!
//        } else {
//            $errors = $resp->getErrorCodes();
//        }

            $len = count($logId);
            while ($len > -1) {
                if ($log[$len] == strip_tags($_POST['log']) && $logPass[$len] == strip_tags($_POST['password'])) {
                    if (!empty($_POST['remem'])) {
                        setcookie('auth', '1', time() + 1800, '/');
                    }
                    $_SESSION['auth'] = true;
                    $_SESSION['user_id'] = $logId[$len];
                    $_SESSION['login'] = $log[$len];
                    $isAuth = $_SESSION['auth'];
//                    header('HTTP/1.1 404 Not Found');
                    header('Location: ?url=lk');
//                    exit();
                }
                $len--;
            }
        }
    }
}


